---
- name: Install Apache and Deploy Files from GitHub
  hosts: all
  become: true
  vars:
    github_repo: "https://github.com/leogamer644/shortener"
    destination_dir: "/var/www/html"

  tasks:
    - name: Add repo forgot name
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      state: present

    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure git is installed
      apt:
        name: git
        state: present
        update_cache: yes
    - name: Ensure grafana is installed
          apt:
            name: grafana
            state: present
            update_cache: yes

    - name: Clone GitHub repository
      git:
        repo: "{{ github_repo }}"
        dest: "{{ destination_dir }}"
        version: HEAD
        force: yes

    - name: Set correct permissions for the web directory
      file:
        path: "{{ destination_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Ensure Apache is enabled and running
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Restart service grafana
      ansible.builtin.service:
        name: grafana
        state: started
        enabled: yes
