Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: 80
    # Run Ansible from the Vagrant Host
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
end
